remote_theme: pages-themes/slate
title: 游戏设计思考录
description: 数值设计、系统策划与玩家体验的深度思考
author: ShiroisWhite

markdown: kramdown
highlighter: rouge

# 必须启用这个插件才能使用remote_theme
plugins:
  - jekyll-remote-theme

# 基本的kramdown配置
kramdown:
  input: GFM
  syntax_highlighter: rouge
