title: 游戏设计思考录
description: 数值设计、系统策划与玩家体验的深度思考
author: ShiroisWhite

theme: minima
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false

# GitHub Pages 数学公式支持
math_engine: mathjax
