remote_theme: daattali/beautiful-jekyll
title: 游戏设计思考录
description: 数值设计、系统策划与玩家体验的深度思考
author: ShiroisWhite

# 作者信息
author:
  name: ShiroisWhite
  email: 你的邮箱

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme

# 启用数学公式
use_math: true

# 网站设置
navbar-links:
  关于: "index"
  
# 社交链接（可选）
social-network-links:
  github: 你的GitHub用户名
  linkedin: 你的LinkedIn
